# Generated by Django 4.0.6 on 2024-07-12 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': '公司类型',
                'verbose_name_plural': '公司类型',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': '工作类型',
                'verbose_name_plural': '工作类型',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': '科目类型',
                'verbose_name_plural': '科目类型',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='题目')),
                ('answer', models.TextField(verbose_name='答案')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='关键字')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('interview_at', models.DateField(auto_now=True, verbose_name='考察时间')),
                ('badge', models.CharField(blank=True, default='互联网 计算机 面试', max_length=200, null=True, verbose_name='标签')),
                ('read_count', models.IntegerField(default=2, verbose_name='阅读数量')),
                ('author', models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='作者')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interview.company', verbose_name='科目')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interview.job', verbose_name='工作类型')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interview.subject', verbose_name='科目')),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('body', models.TextField(blank=True, default='', null=True, verbose_name='正文')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='关键字')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('interview_at', models.DateField(auto_now=True, verbose_name='考察时间')),
                ('read_count', models.IntegerField(default=2, verbose_name='阅读数量')),
                ('badge', models.CharField(blank=True, default='互联网 后端', max_length=200, null=True, verbose_name='标签')),
                ('classification', models.IntegerField(choices=[(1, '实习'), (2, '校招'), (3, '社招')], default=2, verbose_name='分类')),
                ('author', models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='作者')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interview.company', verbose_name='公司')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interview.job', verbose_name='工作类型')),
            ],
            options={
                'verbose_name': '面经',
                'verbose_name_plural': '面经',
            },
        ),
    ]
