# Generated by Django 4.0.6 on 2024-07-12 03:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(max_length=200, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('photo', models.CharField(default='https://cdn.acwing.com/media/user/profile/photo/149733_md_15a86531ae.jpg', max_length=256)),
                ('state', models.IntegerField(default=0, verbose_name='状态')),
                ('registere', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('login_time', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
